version: '3.7'
networks:
  outside:
    external:
      name: studyctrl-network
  inside:
    driver: bridge
  traefik-net:
    external: true

services:
  # builds the frontend
  collab-writing-with-ai-frontend:
    container_name: collab-writing-with-ai-frontend
    build:
      context: ./
      dockerfile: Dockerfile.prod
    networks:
      - inside
    volumes:
      - ./build/:/ui/build/
      - ./public:/ui/public
      - ./src/:/ui/src/
  # serves the frontend
  collab-writing-with-ai-nginx:
    container_name: collab-writing-with-ai-frontend
    image: nginx
    ports:
      - 8876:80
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./build:/frontend/public
    depends_on:
      - collab-writing-with-ai-frontend
    networks:
      - inside
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.port=8088" # port of the traefik instance
      - "traefik.docker.network=traefik-net" # traefik network
      - "traefik.http.routers.collab-writing-with-ai.rule=PathPrefix(`/collab-writing-with-ai`)" # URL path to your backend, replace YOUR-BACKEND with an unique string to name your router
      - "traefik.http.middlewares.collab-writing-with-ai.stripprefix.prefixes=/collab-writing-with-ai" # declare strip prefix middleware from above, replace strip-YOUR-PATH with an unique name
      - "traefik.http.routers.collab-writing-with-ai.middlewares=collab-writing-with-ai@docker" # add middleware that strips of your path, replace YOUR-BACKEND with the router name above, replace strip>

